language: python

python:    
 - "3.6.1"
 
services:
  - postgres

install:    
 - pip install -r requirements.txt
 - pip install codeclimate-test-reporter
 
before_script:
  - psql -c "create database store_manager_api;" -U postgres
  - psql -c "create user postgres;" -U postgres
script:    
 
 -  python -m pytest --cov=app
 - coveralls
 
after_success:
 - coveralls
 - codeclimate-test-reporter
